
FACEBOOK_APP_KEY: '600587946754815'
FACEBOOK_APP_SECRET: b602659eb6f871fde7bd3b32c2fa9258

AWS_KEY_ID:    'AKIAIV4U3AQ6G6RRGI5Q'
AWS_SECRET_KEY: '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'
AWS_BUCKET_NAME: 'airbnbbucket'

BRAINTREE_MERCHANT_ID: 'yfm9sg6fyzhzqmvy'
BRAINTREE_PUBLIC_KEY: 'xcybgbgs84jf2tqc'
BRAINTREE_PRIVATE_KEY: 'c6623e6f8538524f11e908216bc661c2'

gmail_username: 'cheryl.siew.next@gmail.com'
gmail_password: 'cswmn^6688'